[tools]
ruby = "3.2.2"
python = "3.10"
go = "1.21"
node = "18"
dotnet = "8.0.100"
awscli = "2.13.3"
dasel = "2.3.6"
java = "21"
jq = "latest"
deploy1 = "latest"
yarn = "1.22.19"

[settings]
trusted_config_paths = ["~/Desktop/Projects/"]
experimental = true

[plugins]
deploy1 = "https://github.com/Leo-Campo/rtx-deploy1-plugin"
