# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  full-install-ubuntu:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: large
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: "git submodule update --init --recursive"
      - run:
          name: "Install dependencies"
          command: "./install --only omnipkg"
      - run:
          name: "Install rust"
          command: "./.dotbot/scripts/rustup.sh"
      - run:
          name: "Install tools"
          command: "./install --only shell -vv"
      - run:
          name: "Link configuration files"
          command: "./install --only link"

  linking-ubuntu:
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Link configuration files"
          command: "./install --only link"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  full-install-ubuntu:
    jobs:
      - full-install-ubuntu:
          filters:
            branches:
              only: main
  linking-ubuntu:
    jobs:
      - linking-ubuntu:
          filters:
            branches:
              only: dev
